RPI-HASS/rpi_csdt_community

- bin/setup.sh
Thanks to @chuck211991 suggesting some changes, hopefully this will allow @joshuacherry to do a database transfer.
> Added postgis to vagrant

- project_share/templates/project_share/project_detail.html
- templates/_project_thumbnail.html
This should fix images.
change the html references from f to file_path
> Fixed mistake on linting

- rpi_csdt_community/settings.py
- templates/account/email/email_confirmation_message.txt
- templates/account/email/email_confirmation_subject.txt
- templates/account/email/password_reset_key_message.txt
- templates/account/email/password_reset_key_subject.txt
Requires local_settings update to include password to csdtrpi@gmail.com
Added email settings
Added custom messages
> Adds email reset

- templates/base.html
Removing an unused font from base.html
> remove unused font from base.html

- cms_bootstrap_templates/templates/cms_bootstrap_templates/template_header_two_column.html
- cms_bootstrap_templates/templates/cms_bootstrap_templates/template_header_two_column_left.html
- cms_bootstrap_templates/templates/cms_bootstrap_templates/template_header_two_column_right.html
- cms_bootstrap_templates/templates/cms_bootstrap_templates/template_one_column.html
- cms_bootstrap_templates/templates/cms_bootstrap_templates/template_three_column.html
- cms_bootstrap_templates/templates/cms_bootstrap_templates/template_two_column.html
- templates/base.html
It's not DRY, but I wanted to keep it out of base for obvious reasons
> Added toolbar to templates

- static/css/csdt.css
- static/less/style.less
Since we're not depricating the CMS immediately these are style changes needed for the CMS to fit the new design
> Style Changes for Maintaning CMS on Live Site Transition

- static/less/style.less
The width of the menu items is now important, (different color) and needs to be set... that has been done here.
> Fix Column Width

- project_share/templates/project_share/application_csnap.html
> Added spanish to the CSnap template

- templates/home.html
Reverts RPI-HASS/rpi_csdt_community#68
> Revert "I think this will make the front cards all the same size"

- templates/_nav.html
- templates/home.html
Makes the white part of the card a fixed 310px height.
> Changes white card to be full size of grey card

- templates/_nav.html
- templates/home.html
Reverts RPI-HASS/rpi_csdt_community#70
> Revert "Changes white card to be full size of grey card"

- project_share/templates/project_share/application_list.html
- rpi_csdt_community/urls.py
- rpi_csdt_community/views.py
- static/css/base.css
- static/css/csdt.css
- static/js/create/create.html
Swaps the cards homepage out for the angular "themes" application_list.
> Angular list

- rpi_csdt_community/serializers.py
- static/js/create/app.js
- static/js/create/create.html
Added a function that sorts applications by rank
After applications and categories load, sort category by aforementioned sort
Update the CSnap & Modules
> Cateogories uses rank now

- project_share/templatetags/project_share_tags.py
- templates/django_teams/fragments/django_teams/ownership.html
- templates/django_teams/fragments/project_share/project.html
- templates/django_teams/team_form.html
Adding classroom name, description, and edit at top
Switch from clickable items to check boxes
Fix display of ownership items
> Improving Classroom Layout

- templates/django_teams/_table.html
- templates/django_teams/team_list.html
This should inject teams you're a member/admin of at the top of the list. It's not really DRY but I'm avoiding going into the django_teams code to make new contexts. Think this is acceptable?
> Shows team in which you're a current member at top of the list

- templates/django_teams/fragments/project_share/extendeduser.html
Adds avatar to classroom members otherwise defaults to blue outline image
> Class avatar

- requirements.txt
- rpi_csdt_community/settings.py
- rpi_csdt_community/urls.py
Added it to requirements, installed_apps, and URLs
> Added django_pre_post

- project_share/templates/project_share/user_detail.html
Adds a check to see if viewing another person's profile. If so, then the page is formatted in second person instead of first person narrative.  It also removes the "edit profile" & "change password" buttons.
> Adds checks to see if viewing another's profile, formats accordingly

- templates/_paginate.html
Adds a "first" for the first page of search results in a paginated list, and a "last" for the last page of paginated results.
> Adds first and last to search results pagination

- templates/_login.html
- templates/_nav.html
Adds Sign Up to the RHS of the nav bar, next to Log In
> Adds a 'Sign Up' to the RHS nav bar

- project_share/templates/project_share/application_list_react.html
- static/js/create_react/src/js/AppList.js
Attempt at implementing the right hand boxing of the CSDT intro text on the menu page. It's squeezed small and rectangular at small screen sizes, but at 1200px becomes the right hand size small box Ron requested.
> Front page

- rpi_csdt_community/urls.py
> Changed favicon redirect to serve static

- templates/django_teams/fragments/project_share/project.html
> Now it says who the owner is, for easier grading

- requirements.txt
- rpi_csdt_community/urls.py
- templates/_nav.html
> Rollback static about

- blogposts/admin.py
> Creator for Blog Posts will Default to The Current User

- rpi_csdt_community/fixtures/test_data.json
- rpi_csdt_community/tests.py
- rpi_csdt_community/viewsets.py
Adding tests for user data, api specific project, demos, and goals
Removing useless lines for django 1.5 and print out
> Improving Coverage

- .coveragerc
- .travis.yml
- blogposts/tests.py
- blogposts/urls.py
- blogposts/views.py
- project_share/fixtures/default.json
- project_share/forms.py
- project_share/tests/test_views.py
- project_share/urls.py
- project_share/views.py
Fixed travis file to cover ALL files, not just rpi_csdt_community
Added coverage file to ignore migrate etc.
Added test to blog for create, view, comment, delete comment
Removed blog views for create and delete
Fixed fixtures for appliction in project_share
Added tests for project, application, and user views in project_share
Removed address views in project_share
> Fixing Testing

- .gitmodules
Adding the submodule to the git submodules
> Add fractal explorer

- rpi_csdt_community/templates/rpi_csdt_community/publications.html
Prof. Eglash noticed a publication entry missing a journal name.
> Updating journal entry on publications

- rpi_csdt_community/templates/rpi_csdt_community/publications.html
Just double checked and noticed a few more missing citations.
> Publicat update

- blogposts/tests.py
Pushing to develop instead of master
> Add testing

- blogposts/tests.py
- blogposts/views.py
- project_share/fixtures/default.json
- project_share/tests/test_views.py
Adding post to comment thread
Adding contexts to the fixtures
Adding a test for contexts
Removing excess print statements
> Go Go Testing

- requirements.txt
Should give us good django PRs now.
> New PyUp Filter For LTS

- rpi_csdt_community/templates/rpi_csdt_community/about.html
Noticed a spelling mistake: Ethomath => Ethnomath on about template
> Spelling of ethno

- rpi_csdt_community/templates/rpi_csdt_community/publications.html
Adds Bill as an author of the Generative Justice article.
> Adding bill as author

- project_share/templates/project_share/project_detail.html
Reverts RPI-HASS/rpi_csdt_community#565
> Revert "remove comments"

- rpi_csdt_community/templates/rpi_csdt_community/starting.html
To test CSnap 2d library online.
> Force django update

- rpi_csdt_community/templates/rpi_csdt_community/about.html
Random comment to force django update
> Forcing update again for Darwin Game Online Testing

- rpi_csdt_community/settings.py
I am updating the ID for Google Analytics. (Ron got a new id)
> Google Analytics

- rpi_csdt_community/settings.py
- templates/base.html
New function as recommended by google analytics
> Google analytics update
