rpi_csdt_community/settings.py
rpi_csdt_community/urls.py

This updates the catch-all regex at the end of urls.py from /collected_static to just /static, because our static files exist there and aren't collected into collected_static.

Urls static

---

rpi_csdt_community/urls.py

Fixing the catchall problem of having ending slashes breaking links and apis by just putting the static pages under the /culture/ prefix.

Regex prefix

---

static/css/csdt.css
templates/base.html

I noticed the svgs at the bottom of the page were becoming a vertical line on cell phone sizes so I took out the large margins from desktop mode on the cell phone media query.

Footer small

---

rpi_csdt_community/urls.py

Changes urls.py to use settings.STATIC_WEBSITE_ROOT (which points to static/website/www) instead of settings.STATIC_ROOT (which points to collected_static/)

Changing urls.py to use STATIC_WEBSITE_ROOT instead of STATIC_ROOT

---

static/css/base.css

There was an error when hovering over the button on the blog only caused the lower half of the button to change color. I couldn't find an easy fix, so I'm using this kind of hacky way to keep the button a single solid color (but it works!)

Changes button to full coverage

---

blogposts/templates/post_detail.html
blogposts/templates/post_list.html
project_share/templates/project_share/application_list.html
static/css/blog.css

Boots up the font-size on the blog template. Also getting rid of the base.css, which existed for the old bootstrap static cards we had for the home page, which was replaced by the angular menu.

Swapping out base.css for blog.css on blog pages

---

blogposts/admin.py

As per Bill's request, this should make the "create new blog post" admin panel autofill the current user for the "posted by" field.

Should default to current user now when making a blog post

---

project_share/templates/project_share/project_filter.html

I noticed just now that "clear search" wasn't showing up if you filtered by project or search. I'm not sure how that slipped by us, at least I thought I remember it working correctly... Nevertheless, here is a fixed to make sure that "clear search" is visible whether filtering, sorting, or searching (and any combination thereof).

Fixes logic in filtering protocol so that 'clear search' always shows

---

static/css/csdt.css

Most buttons on the site are being divided in half based on some bizarre :hover css in the less file. It creates a background-position: 0px -15px; on all hover states.
This overrides that css and makes a background-position: 0px 0px; button hover state.

Buttons are halved

---

rpi_csdt_community/templates/rpi_csdt_community/about.html

Line length (that the 45th and 75th characters in a sentence shouldn't be on the same line //
http://typographyforlawyers.com/line-length.html) was too long for the About page, and it was also aligned too far to the left, so I made the paragraphs tighter and center aligned.

Fixing line length

---

templates/_project_thumbnail.html

Stretches the image in project thumbnail to width of container div. Removes description and shrinks the total height of the card.
I didn't get to test this on a large set of projects, so if there are some outliers that make it break or whatever let me know.

project_thumbnail: Stretching image and shrinking height

---

templates/_project_thumbnail.html

last update caused some scroll boxes to appear if the name was multi lined.
This should give it enough wiggle room.
changed "320px" to "340px"

Overshot it

---

project_share/templates/project_share/project_filter.html

Changes the search result parameter to be paginator.count instead of object_list|length because that was just returning "20" multiple times since the results were paginated.

Adds total number of search results, not just paginated 20

---

blogposts/templates/post_list.html
static/css/blog.css
templates/_paginate.html

Making pagination text larger

---

static/css/csdt.css
templates/_nav.html

Replaces the .jpg logo with an embedded svg logo, which allows hover-over effects. Removes "application" redundant link. Lightens navbar text color to ```#d8d8d8```.

SVG'izes the logo and lightens text, with transitions on hover

---

blogposts/templates/post_detail.html

Adds author's name to blog posts, which Bill requested. It was originally in there, but the code was broken/requested a helper function that didn't exist on the user model.

Fixes author's name in blog posts

---

blogposts/templates/post_detail.html

Addresses #316 
Just removes the "reply" link from blog comments. I never realized this wasn't implemented (good catch!), and given no one really comments it seems easier just to block thread all replies instead of implementing threading.

Remove reply

---

rpi_csdt_community/templates/rpi_csdt_community/about.html

Adds three lines under a "video tutorial" category on the about page. In future we will flesh out a self-standing video tutorial page with many videos, but this is just for now until we make those tutorials.

Adds a few lines for classroom video tutorials on about page

---

rpi_csdt_community/templates/rpi_csdt_community/about.html

Adds a disclaimer about personal views not reflecting those of the NSF onto the About page.
As requested by Bill.

Update about page to include NSF disclaimer

---

templates/base.html

Looks like the original way of reading from the settings.py file for the tag is tempermental. So to get it working, I have it hard coded into the base html file.

Hardcode google analytics in base html
